import {
  ActiveCall,
  CallLog,
  CampaignData,
  Contact,
  CrmIntegration,
  CrmSyncLog,
  LiveAgent,
  QoSThresholdConfig,
  ScheduledFollowUp,
  SessionQoSTelemetry,
  TwilioConfig,
  TwilioDID,
} from '../types/telephony';

export const DEFAULT_QOS_THRESHOLDS: QoSThresholdConfig = {
  jitterWarningMs: 25,
  jitterCriticalMs: 45,
  packetLossWarningPercent: 2.0,
  packetLossCriticalPercent: 4.5,
  mosWarningScore: 3.8,
  autoRemediation: true,
  alertSound: true,
  visualHudEnabled: true,
};

export const INITIAL_AGENTS: LiveAgent[] = [
  {
    id: 'agent-1',
    name: 'Sarah Jenkins',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    status: 'talking',
    durationInState: 252, // 04:12
    callerName: 'Marcus Sterling',
    campaign: 'Tier 1 Customer Care & Support',
    skills: ['Tier 1 Support', 'Billing', 'SIP'],
    priorityRank: 2,
    qos: {
      jitterMs: 9.4,
      packetLossPercent: 0.12,
      rttMs: 22,
      mosScore: 4.42,
      codec: 'Opus HD (48kHz)',
      bitrateKbps: 64,
      bufferLatencyMs: 20,
      packetsLost: 4,
      packetsTotal: 3420,
      edgeGateway: 'us-east-ashburn-01',
      warningType: 'none',
      severity: 'normal',
      history: [
        { time: '14:32:00', jitter: 8.2, packetLoss: 0.08, mos: 4.45 },
        { time: '14:32:15', jitter: 9.1, packetLoss: 0.10, mos: 4.43 },
        { time: '14:32:30', jitter: 10.4, packetLoss: 0.15, mos: 4.40 },
        { time: '14:32:45', jitter: 8.8, packetLoss: 0.09, mos: 4.44 },
        { time: '14:33:00', jitter: 9.4, packetLoss: 0.12, mos: 4.42 },
      ],
    },
  },
  {
    id: 'agent-2',
    name: 'David Ross',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    status: 'ready',
    durationInState: 24, // 00:24
    callerName: undefined,
    campaign: 'VIP Escalations & Retention',
    skills: ['Escalations', 'VIP Retain', 'Technical'],
    priorityRank: 1,
  },
  {
    id: 'agent-3',
    name: 'Elena Rostova',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    status: 'wrapup',
    durationInState: 45, // 00:45
    callerName: undefined,
    campaign: 'Q3 Enterprise SaaS Renewals',
    skills: ['SaaS Contracts', 'Closing', 'Spanish'],
    priorityRank: 3,
    gracePeriodLeft: 15,
  },
  {
    id: 'agent-4',
    name: 'Michael Chang',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    status: 'break',
    durationInState: 494, // 08:14
    callerName: undefined,
    campaign: 'Tier 1 Customer Care & Support',
    skills: ['Tier 1 Support'],
    priorityRank: 4,
  },
  {
    id: 'agent-5',
    name: 'Marcus Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
    status: 'talking',
    durationInState: 148,
    callerName: 'Emily Watson',
    campaign: 'Mortgage Pre-Approval Warm Leads',
    skills: ['Mortgage Lending', 'Outbound Sales'],
    priorityRank: 5,
    qos: {
      jitterMs: 38.6, // Exceeds warning threshold 25ms!
      packetLossPercent: 1.85,
      rttMs: 84,
      mosScore: 3.65,
      codec: 'Opus HD (48kHz)',
      bitrateKbps: 48,
      bufferLatencyMs: 65,
      packetsLost: 48,
      packetsTotal: 2590,
      edgeGateway: 'us-west-oregon-02',
      warningType: 'jitter',
      severity: 'warning',
      history: [
        { time: '14:32:00', jitter: 14.5, packetLoss: 0.4, mos: 4.30 },
        { time: '14:32:15', jitter: 21.2, packetLoss: 0.9, mos: 4.10 },
        { time: '14:32:30', jitter: 31.8, packetLoss: 1.4, mos: 3.85 },
        { time: '14:32:45', jitter: 39.4, packetLoss: 1.9, mos: 3.62 },
        { time: '14:33:00', jitter: 38.6, packetLoss: 1.85, mos: 3.65 },
      ],
    },
  },
  {
    id: 'agent-6',
    name: 'Aaliyah Patel',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    status: 'ready',
    durationInState: 68,
    callerName: undefined,
    campaign: 'Tier 1 Customer Care & Support',
    skills: ['Customer Care', 'High Intent'],
    priorityRank: 6,
  },
  {
    id: 'agent-7',
    name: 'Liam Gallagher',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80',
    status: 'talking',
    durationInState: 312,
    callerName: 'Sophia Martinez',
    campaign: 'VIP Escalations & Retention',
    skills: ['VIP Retain', 'Technical Escalations'],
    priorityRank: 7,
    qos: {
      jitterMs: 29.8,
      packetLossPercent: 3.42, // Exceeds packet loss threshold 2.0%!
      rttMs: 98,
      mosScore: 3.28,
      codec: 'G.711u (8kHz)',
      bitrateKbps: 64,
      bufferLatencyMs: 70,
      packetsLost: 112,
      packetsTotal: 3280,
      edgeGateway: 'eu-central-frankfurt-01',
      warningType: 'packet_loss',
      severity: 'warning',
      history: [
        { time: '14:32:00', jitter: 18.0, packetLoss: 1.2, mos: 4.05 },
        { time: '14:32:15', jitter: 24.5, packetLoss: 2.1, mos: 3.70 },
        { time: '14:32:30', jitter: 28.0, packetLoss: 2.9, mos: 3.45 },
        { time: '14:32:45', jitter: 32.1, packetLoss: 3.6, mos: 3.20 },
        { time: '14:33:00', jitter: 29.8, packetLoss: 3.42, mos: 3.28 },
      ],
    },
  },
  {
    id: 'agent-8',
    name: 'Chloe Bennett',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    status: 'talking',
    durationInState: 98,
    callerName: 'Robert Hayes',
    campaign: 'Q3 Enterprise SaaS Renewals',
    skills: ['SaaS Contracts', 'Closing'],
    priorityRank: 8,
    qos: {
      jitterMs: 11.2,
      packetLossPercent: 0.08,
      rttMs: 25,
      mosScore: 4.41,
      codec: 'Opus HD (48kHz)',
      bitrateKbps: 64,
      bufferLatencyMs: 25,
      packetsLost: 2,
      packetsTotal: 1840,
      edgeGateway: 'us-east-ashburn-02',
      warningType: 'none',
      severity: 'normal',
      history: [
        { time: '14:32:00', jitter: 10.5, packetLoss: 0.06, mos: 4.42 },
        { time: '14:32:15', jitter: 11.8, packetLoss: 0.09, mos: 4.40 },
        { time: '14:32:30', jitter: 12.0, packetLoss: 0.10, mos: 4.39 },
        { time: '14:32:45', jitter: 10.9, packetLoss: 0.07, mos: 4.42 },
        { time: '14:33:00', jitter: 11.2, packetLoss: 0.08, mos: 4.41 },
      ],
    },
  },
];

export const INITIAL_CAMPAIGNS: CampaignData[] = [
  {
    id: 'cam-in-01',
    name: 'Tier 1 Customer Care & Support',
    type: 'Inbound ACD',
    status: 'STABLE',
    queueSize: 14,
    estWaitTime: '42s',
    serviceLevel: '92.4%',
    agentsLogged: 32,
    agentsTalking: 24,
    agentsReady: 5,
    agentsWrap: 3,
    connectRate: '98.5%',
  },
  {
    id: 'cam-in-02',
    name: 'VIP Escalations & Retention',
    type: 'Priority Inbound',
    status: 'OPTIMAL',
    queueSize: 2,
    estWaitTime: '12s',
    serviceLevel: '98.1%',
    agentsLogged: 12,
    agentsTalking: 8,
    agentsReady: 4,
    agentsWrap: 0,
    connectRate: '99.4%',
  },
  {
    id: 'cam-out-01',
    name: 'Q3 Enterprise SaaS Renewals',
    type: 'Predictive',
    status: 'DIALING (OPTIMIZED)',
    queueSize: 0,
    estWaitTime: '0s',
    serviceLevel: '94.8%',
    agentsLogged: 18,
    agentsTalking: 14,
    agentsReady: 3,
    agentsWrap: 1,
    connectRate: '44.2%',
    conversionRate: '16.8%',
    dialed: 3420,
    leadsLeft: 1840,
    pacingRatio: '2.4x',
    dropRate: '1.1%',
  },
  {
    id: 'cam-out-02',
    name: 'Mortgage Pre-Approval Warm Leads',
    type: 'Progressive',
    status: 'RUNNING',
    queueSize: 0,
    estWaitTime: '0s',
    serviceLevel: '91.2%',
    agentsLogged: 14,
    agentsTalking: 10,
    agentsReady: 3,
    agentsWrap: 1,
    connectRate: '58.7%',
    conversionRate: '18.2%',
    dialed: 1980,
    leadsLeft: 940,
    pacingRatio: '1.0x Preview (30s)',
    dropRate: '0.4%',
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cnt-1',
    name: 'Jonathan Vance',
    title: 'VP of Telecom Infrastructure',
    phone: '+1 (415) 890-2341',
    email: 'j.vance@apexdataworks.io',
    company: 'Apex Global Dataworks Inc.',
    arr: '$120,000',
    priority: 'VIP Enterprise',
    campaign: 'Q3 Enterprise SaaS Renewals',
    status: 'Connected',
    timezone: 'America/Los_Angeles (11:42 AM PST)',
    contractExpiryDays: 45,
    notes: 'Reviewing migration brief for high-throughput dedicated trunk tier. Requesting 15% multi-year lock-in.',
  },
  {
    id: 'cnt-2',
    name: 'Marcus Sterling',
    title: 'Chief Technology Officer',
    phone: '+1 (212) 555-0192',
    email: 'm.sterling@fintechglobal.com',
    company: 'FinTech Global Capital',
    arr: '$240,000',
    priority: 'VIP Enterprise',
    campaign: 'Tier 1 Customer Care & Support',
    status: 'Dialed',
    timezone: 'America/New_York (02:42 PM EST)',
    contractExpiryDays: 82,
    notes: 'Inquired about sub-20ms RTT SIP gateway redundancy in US-East Ashburn.',
  },
  {
    id: 'cnt-3',
    name: 'Elena Rostova',
    title: 'Head of Infrastructure',
    phone: '+1 (617) 555-0187',
    email: 'elena@cloudventure.tech',
    company: 'CloudVenture Systems',
    arr: '$85,000',
    priority: 'Mid-Market',
    campaign: 'Q3 Enterprise SaaS Renewals',
    status: 'New',
    timezone: 'America/New_York (02:42 PM EST)',
    contractExpiryDays: 30,
    notes: 'Contract expiring in 30 days. Needs executive overview document.',
  },
  {
    id: 'cnt-4',
    name: 'David Kim',
    title: 'VP of Engineering',
    phone: '+1 (312) 440-1920',
    email: 'dkim@secureauth.io',
    company: 'SecureAuth Networks',
    arr: '$195,000',
    priority: 'VIP Enterprise',
    campaign: 'Tier 1 Customer Care & Support',
    status: 'Won',
    timezone: 'America/Chicago (01:42 PM CST)',
    contractExpiryDays: 140,
    notes: 'MFA integration and PCI-DSS IVR vaulting configured successfully.',
  },
  {
    id: 'cnt-5',
    name: 'Sarah Lin',
    title: 'Director of Operations',
    phone: '+1 (512) 789-2041',
    email: 'slin@biohealthcorp.org',
    company: 'BioHealth Corp',
    arr: '$65,000',
    priority: 'Standard',
    campaign: 'Mortgage Pre-Approval Warm Leads',
    status: 'Follow-up',
    timezone: 'America/Chicago (01:42 PM CST)',
    contractExpiryDays: 110,
    notes: 'Demo booked for next Tuesday 2 PM CST.',
  },
  {
    id: 'cnt-6',
    name: 'Amanda Patel',
    title: 'VP of Supply Chain',
    phone: '+1 (206) 555-8912',
    email: 'amanda@meridianlogistics.com',
    company: 'Meridian Logistics Group',
    arr: '$140,000',
    priority: 'VIP Enterprise',
    campaign: 'Q3 Enterprise SaaS Renewals',
    status: 'New',
    timezone: 'America/Los_Angeles (11:42 AM PST)',
    contractExpiryDays: 20,
    notes: 'Urgent renewal window approaching before Q4 freeze.',
  },
  {
    id: 'cnt-7',
    name: 'Robert Hayes',
    title: 'Lead Architect',
    phone: '+1 (303) 441-9023',
    email: 'rhayes@apexnetworks.com',
    company: 'Apex Networks Denver',
    arr: '$95,000',
    priority: 'Mid-Market',
    campaign: 'Mortgage Pre-Approval Warm Leads',
    status: 'New',
    timezone: 'America/Denver (12:42 PM MST)',
    contractExpiryDays: 60,
  },
  {
    id: 'cnt-8',
    name: 'Tanya Gomez',
    title: 'Finance Director',
    phone: '+1 (786) 304-1189',
    email: 'tgomez@latamtrade.com',
    company: 'LATAM Trade Hub',
    arr: '$110,000',
    priority: 'Mid-Market',
    campaign: 'VIP Escalations & Retention',
    status: 'New',
    timezone: 'America/New_York (02:42 PM EST)',
    contractExpiryDays: 95,
  },
];

export const INITIAL_CALL_LOGS: CallLog[] = [
  {
    id: 'call-log-1',
    callId: 'CALL-98241',
    timestamp: '2026-09-26 14:32:10 EST',
    callerName: 'Sarah Lin',
    callerPhone: '+1 (312) 440-1920',
    company: 'BioHealth Corp',
    direction: 'inbound',
    agentName: 'AI Voice Agent (BillingBot-v4)',
    campaign: 'Tier 1 Customer Care & Support',
    duration: 134, // 2m 14s
    outcome: 'Follow Up Required',
    recordingUrl: 'https://cdn.aetherdial.com/recordings/call-98241.mp3',
    hasAudio: true,
    transcription: 'Caller requested corporate credit card update and confirmation of zero overage billing. Automated MFA verification completed.',
    sentimentScore: 88,
    followUpDate: '2026-09-28',
    cost: 0.12,
    aiGenerated: true,
    aiSummaryTimestamp: '2026-09-26 14:34:25 EST',
    summary: 'Sarah Lin completed automated biometric MFA verification to update corporate payment credentials and confirmed zero overage billing policy for BioHealth Corp.',
    keyTakeaways: [
      'Successfully verified caller identity using voice biometric and SMS one-time passcode.',
      'Updated primary billing payment method to corporate Amex ending in 4092.',
      'Confirmed zero-overage billing policy applies across both US-East and US-Central gateways.',
      'Customer requested email receipt and updated master services agreement annex.',
    ],
    actionItems: [
      'Dispatch updated MSA billing annex via automated email webhook.',
      'Schedule automated account check-in for September 28, 2026.',
    ],
    sentimentAnalysis: 'Highly positive and cooperative (88% CSAT indicator). Quick resolution achieved.',
  },
  {
    id: 'call-log-2',
    callId: 'CALL-98239',
    timestamp: '2026-09-26 14:30:45 EST',
    callerName: 'Jonathan Vance',
    callerPhone: '+1 (415) 890-2341',
    company: 'Apex Global Dataworks Inc.',
    direction: 'outbound',
    agentName: 'Sarah Chen',
    campaign: 'Q3 Enterprise SaaS Renewals',
    duration: 222, // 3m 42s
    outcome: 'Contract Sent',
    recordingUrl: 'https://cdn.aetherdial.com/recordings/call-98239.mp3',
    hasAudio: true,
    transcription: 'Jonathan confirmed satisfaction with proposed 15% multi-year contract discount. DocuSign agreement dispatched for VP of Tech countersignature.',
    sentimentScore: 82,
    followUpDate: '2026-09-29',
    cost: 0.38,
    aiGenerated: true,
    aiSummaryTimestamp: '2026-09-26 14:34:28 EST',
    summary: 'Jonathan Vance agreed to multi-year enterprise license renewal with 15% discount lock-in; DocuSign package dispatched with executive sign-off deadline set for Thursday.',
    keyTakeaways: [
      'Customer confirmed budget approval for 3-year term renewal valued at $120,000 ARR.',
      'Validated 15% multi-year discount covers secondary disaster recovery trunk in Dallas cluster.',
      'Customer noted VP of Tech signature is scheduled for executive review this Thursday.',
      'DocuSign envelope #ENV-9281 dispatched with clause 4.2 99.98% SLA intact.',
    ],
    actionItems: [
      'Monitor DocuSign envelope status for countersignature before Thursday 5 PM PST.',
      'Prepare welcome onboarding package for secondary Dallas SIP trunk activation.',
      'Schedule follow-up reminder for Tuesday, September 29, 2026.',
    ],
    sentimentAnalysis: 'Very confident and enthusiastic (82% sentiment); pricing objection proactively handled.',
  },
  {
    id: 'call-log-3',
    callId: 'CALL-98228',
    timestamp: '2026-09-26 14:26:12 EST',
    callerName: 'Elena Rostova',
    callerPhone: '+1 (617) 555-0187',
    company: 'CloudVenture Systems',
    direction: 'outbound',
    agentName: 'Sarah Chen',
    campaign: 'Q3 Enterprise SaaS Renewals',
    duration: 185, // 3m 05s
    outcome: 'Interested / Demo',
    recordingUrl: 'https://cdn.aetherdial.com/recordings/call-98228.mp3',
    hasAudio: true,
    transcription: 'Customer reviewed migration brief. Requested follow-up session with Enterprise Solutions Architect to evaluate dual-region SIP trunk failover.',
    sentimentScore: 76,
    followUpDate: '2026-09-30',
    cost: 0.29,
    aiGenerated: true,
    aiSummaryTimestamp: '2026-09-26 14:29:20 EST',
    summary: 'Elena Rostova expressed strong technical interest in dual-region SIP trunk failover; requested architecture validation meeting with Solutions Engineering.',
    keyTakeaways: [
      'Contract expires in 30 days ($85,000 ARR); customer actively evaluating carrier redundancy.',
      'Key technical requirement: sub-100ms automated failover between US-East and Frankfurt gateway.',
      'Requested technical architecture briefing with assigned Solutions Architect.',
      'Provided ROI assessment demonstrating 24% cost reduction over legacy carrier.',
    ],
    actionItems: [
      'Book Solutions Architect Marcus Sterling for technical demo on September 30 at 10 AM EST.',
      'Share network topology diagram and SIP latency benchmark report.',
    ],
    sentimentAnalysis: 'Analytical and engaged (76% sentiment); receptive to architectural proof-of-concept.',
  },
  {
    id: 'call-log-4',
    callId: 'CALL-98215',
    timestamp: '2026-09-26 14:21:04 EST',
    callerName: 'David Kim',
    callerPhone: '+1 (212) 555-0192',
    company: 'SecureAuth Networks',
    direction: 'inbound',
    agentName: 'AI Voice Agent (AuthBot-v1)',
    campaign: 'VIP Escalations & Retention',
    duration: 72, // 1m 12s
    outcome: 'Completed Sale',
    recordingUrl: 'https://cdn.aetherdial.com/recordings/call-98215.mp3',
    hasAudio: true,
    transcription: 'Completed biometric and MFA voice authorization for dedicated secondary SIP cluster in US-West gateway.',
    sentimentScore: 94,
    cost: 0.08,
    aiGenerated: true,
    aiSummaryTimestamp: '2026-09-26 14:22:20 EST',
    summary: 'David Kim completed voice biometric authorization and finalized order for dedicated secondary SIP cluster expansion on US-West gateway.',
    keyTakeaways: [
      'Expansion deal closed: +$75,000 added ARR for dedicated secondary gateway in Oregon.',
      'Passed Tier-1 cryptographic identity verification via voiceprint matching.',
      'Automated provisioning trigger dispatched to carrier trunk routing pool.',
    ],
    actionItems: [
      'Confirm automated SIP trunk provisioning status in Trunk Routing console.',
      'Send confirmation invoice and API token to SecureAuth DevOps team.',
    ],
    sentimentAnalysis: 'Extremely positive and satisfied (94% sentiment); seamless AI self-service flow.',
  },
  {
    id: 'call-log-5',
    callId: 'CALL-98202',
    timestamp: '2026-09-26 14:15:30 EST',
    callerName: 'Marcus Sterling',
    callerPhone: '+1 (212) 555-0192',
    company: 'FinTech Global Capital',
    direction: 'inbound',
    agentName: 'Sarah Jenkins',
    campaign: 'Tier 1 Customer Care & Support',
    duration: 252, // 4m 12s
    outcome: 'Interested / Demo',
    recordingUrl: 'https://cdn.aetherdial.com/recordings/call-98202.mp3',
    hasAudio: true,
    transcription: 'Discussed latency performance and SLA compliance on Tier-1 SIP routes. Scheduled executive briefing.',
    sentimentScore: 89,
    followUpDate: '2026-10-02',
    cost: 0.42,
    aiGenerated: true,
    aiSummaryTimestamp: '2026-09-26 14:19:45 EST',
    summary: 'Marcus Sterling inquired regarding Opus 48kHz audio codec fidelity and sub-20ms RTT guarantees for high-frequency algorithmic trade desk calling.',
    keyTakeaways: [
      'FinTech Global Capital seeking carrier-grade low latency connectivity with zero jitter.',
      'Validated STIR/SHAKEN Level-A attestation for all algorithmic trading phone lines.',
      'Customer requested custom SLA terms with financial backing for call completion rates.',
    ],
    actionItems: [
      'Prepare customized SLA contract draft with 99.999% carrier availability clause.',
      'Confirm executive briefing on October 2, 2026 at 11:30 AM EST.',
    ],
    sentimentAnalysis: 'Serious, professional, highly receptive to performance telemetry metrics.',
  },
  {
    id: 'call-log-6',
    callId: 'CALL-98194',
    timestamp: '2026-09-26 14:02:18 EST',
    callerName: 'Unregistered Caller',
    callerPhone: '+1 (800) 555-0199',
    company: 'RoboCaller Lead Gen',
    direction: 'inbound',
    agentName: 'IVR Auto-Deflect',
    campaign: 'Tier 1 Customer Care & Support',
    duration: 15,
    outcome: 'Wrong Number / DNC',
    recordingUrl: undefined,
    hasAudio: false,
    transcription: 'Spam solicitation detected by STIR/SHAKEN verification engine. Number added to FCC compliance DNC blacklist.',
    sentimentScore: 10,
    cost: 0.01,
    aiGenerated: true,
    aiSummaryTimestamp: '2026-09-26 14:02:35 EST',
    summary: 'Automated robocall solicitation detected and deflected by STIR/SHAKEN signature filter; number enrolled into carrier Do-Not-Call blacklist.',
    keyTakeaways: [
      'STIR/SHAKEN cryptographic certificate missing (Level-C untrusted origin).',
      'IVR auto-deflected call without ring-through to live agent floor.',
      'Caller phone +1 (800) 555-0199 committed to operational DNC compliance registry.',
    ],
    actionItems: [
      'Verify automated blacklist synchronization with carrier trunk edge.',
    ],
    sentimentAnalysis: 'Hostile/Spam auto-detected; zero agent intervention required.',
  },
];

export const INITIAL_FOLLOW_UPS: ScheduledFollowUp[] = [
  {
    id: 'fup-1',
    contactName: 'Jonathan Vance',
    contactCompany: 'Apex Global Dataworks Inc.',
    contactPhone: '+1 (415) 890-2341',
    contactEmail: 'j.vance@apexdataworks.io',
    scheduledDate: '2026-09-29',
    scheduledTime: '02:00 PM PST',
    assignedAgent: 'Sarah Chen',
    campaign: 'Q3 Enterprise SaaS Renewals',
    notes: 'Follow up on DocuSign countersignature for 15% multi-year dedicated trunk agreement.',
    syncOutlook: true,
    status: 'pending',
    createdAt: '2026-09-26 14:35 EST',
  },
  {
    id: 'fup-2',
    contactName: 'Elena Rostova',
    contactCompany: 'CloudVenture Systems',
    contactPhone: '+1 (617) 555-0187',
    contactEmail: 'elena@cloudventure.tech',
    scheduledDate: '2026-09-30',
    scheduledTime: '10:00 AM EST',
    assignedAgent: 'Sarah Chen',
    campaign: 'Q3 Enterprise SaaS Renewals',
    notes: 'Architecture sync on multi-region failover and SLA benchmarks.',
    syncOutlook: true,
    status: 'pending',
    createdAt: '2026-09-26 14:28 EST',
  },
  {
    id: 'fup-3',
    contactName: 'Marcus Sterling',
    contactCompany: 'FinTech Global Capital',
    contactPhone: '+1 (212) 555-0192',
    contactEmail: 'm.sterling@fintechglobal.com',
    scheduledDate: '2026-10-02',
    scheduledTime: '11:30 AM EST',
    assignedAgent: 'Sarah Jenkins',
    campaign: 'Tier 1 Customer Care & Support',
    notes: 'Executive presentation on Opus 48kHz audio quality and zero packet drop guarantee.',
    syncOutlook: false,
    status: 'pending',
    createdAt: '2026-09-26 14:18 EST',
  },
];

export const INITIAL_TWILIO_CONFIG: TwilioConfig = {
  accountSid: 'AC984f1839201948204918230491c10b',
  authToken: 'SKa9f810184b9281a8f91048f029194',
  edgeLocation: 'Ashburn',
  terminationUri: 'aetherdial-prod.pstn.twilio.com',
  originatingUri: 'sip:inbound@pbx-cluster-east01.aetherdial.internal:5061',
  codecs: ['Opus (Wideband 48kHz HD)', 'G.711u (PCMU 8kHz)', 'G.729a (Low Bandwidth)'],
  failoverSubaccount: true,
  mediaStreamWss: 'telephony-gateway.aetherdial.internal/v1/twilio-media-stream',
  twimlWebhookUrl: 'https://api.aetherdial.com/webhooks/twilio/voice-inbound',
  dtmfRedaction: true,
  symmetricRtp: true,
  stirShaken: true,
  isConnected: true,
  edgeLatencyMs: 18.4,
};

export const INITIAL_DIDS: TwilioDID[] = [
  {
    id: 'did-1',
    number: '+1 (800) 452-9012',
    type: 'Toll-Free',
    assignedCampaign: 'VIP Support ACD',
    friendlyName: 'Toll-Free Enterprise Inbound',
    capabilities: { voice: true, sms: true, mediaStream: true },
    reputation: 'Clean (100%)',
    status: 'Active',
  },
  {
    id: 'did-2',
    number: '+1 (415) 890-2341',
    type: 'Local (SF)',
    assignedCampaign: 'Q3 Enterprise Renewals (Outbound)',
    friendlyName: 'SFO Regional Trunk 01',
    capabilities: { voice: true, sms: true, mediaStream: false },
    reputation: 'Safe (0.8% spam)',
    status: 'Active',
  },
  {
    id: 'did-3',
    number: '+1 (212) 555-0192',
    type: 'Local (NYC)',
    assignedCampaign: 'Commercial Sales East',
    friendlyName: 'NYC Metro Sales Direct',
    capabilities: { voice: true, sms: true, mediaStream: false },
    reputation: 'Clean (100%)',
    status: 'Active',
  },
  {
    id: 'did-4',
    number: '+1 (312) 555-0144',
    type: 'Local (CHI)',
    assignedCampaign: 'Tier-1 Customer Care',
    friendlyName: 'Midwest Support Line',
    capabilities: { voice: true, sms: false, mediaStream: true },
    reputation: 'Clean (100%)',
    status: 'Active',
  },
  {
    id: 'did-5',
    number: '+44 20 7946 0912',
    type: 'Intl (UK)',
    assignedCampaign: 'EMEA Global Queue',
    friendlyName: 'London Gateway 04',
    capabilities: { voice: true, sms: true, mediaStream: false },
    reputation: 'Clean (100%)',
    status: 'Active',
  },
];

export const INITIAL_CRM_INTEGRATIONS: CrmIntegration[] = [
  {
    id: 'crm-1',
    name: 'Salesforce Service Cloud',
    iconName: 'cloud',
    version: 'v61.0',
    status: 'Connected',
    syncMechanism: 'Real-time Webhook',
    targetObject: 'Cases & Contact Hist.',
    lastHandshake: '12s ago',
    slaPriorityRule: 'Tier-1 Escalate',
    autoCreateTrigger: 'Both (Containment & Human Transfer)',
    transcriptAttachment: 'Full JSON + Redacted PII (PCI-DSS)',
    fieldMappings: {
      callerId: 'Contact.Phone',
      notes: 'Case.Description',
      recording: 'Attachment.RecordingUrl',
      sentiment: 'Case.SentimentScore__c',
      disposition: 'Case.Disposition__c',
    },
  },
  {
    id: 'crm-2',
    name: 'Zendesk Enterprise',
    iconName: 'support',
    version: 'Support REST API v2',
    status: 'Connected',
    syncMechanism: 'REST API Polling & Push',
    targetObject: 'Tickets & User Profiles',
    lastHandshake: '45s ago',
    slaPriorityRule: 'Dynamic Priority Matrix',
    autoCreateTrigger: 'Both (Containment & Human Transfer)',
    transcriptAttachment: 'Full JSON + Redacted PII',
    fieldMappings: {
      callerId: 'ticket.requester.phone',
      notes: 'ticket.comment.body',
      recording: 'ticket.custom_fields.recording',
      sentiment: 'ticket.tags.sentiment',
      disposition: 'ticket.status',
    },
  },
  {
    id: 'crm-3',
    name: 'ServiceNow ITOM & CSM',
    iconName: 'dns',
    version: 'Vancouver Edition',
    status: 'Standby',
    syncMechanism: 'OAuth 2.0 Webhook',
    targetObject: 'Incidents & Change Requests',
    lastHandshake: '14m ago',
    slaPriorityRule: 'IT-Helpdesk-Tier2',
    autoCreateTrigger: 'Only on Human Escalation',
    transcriptAttachment: 'Redacted Transcript Only',
    fieldMappings: {
      callerId: 'incident.caller_id',
      notes: 'incident.work_notes',
      recording: 'incident.correlation_id',
      sentiment: 'incident.impact',
      disposition: 'incident.close_code',
    },
  },
  {
    id: 'crm-4',
    name: 'HubSpot CRM',
    iconName: 'hub',
    version: 'v3 REST Engine',
    status: 'Connected',
    syncMechanism: 'Webhook + GraphQL',
    targetObject: 'Deals & Engagements',
    lastHandshake: '2m ago',
    slaPriorityRule: 'Lead Pipeline Auto-advance',
    autoCreateTrigger: 'Create on Disposition',
    transcriptAttachment: 'Call Activity Object',
    fieldMappings: {
      callerId: 'contact.phone',
      notes: 'engagement.body',
      recording: 'call.recording_url',
      sentiment: 'deal.sentiment',
      disposition: 'deal.call_outcome',
    },
  },
];

export const INITIAL_ACTIVE_CALL: ActiveCall = {
  id: 'call-active-01',
  contactName: 'Jonathan Vance',
  contactNumber: '+1 (415) 890-2341',
  contactTitle: 'VP of Telecom Infrastructure',
  company: 'Apex Global Dataworks Inc.',
  arrValue: '$120,000',
  contractExpiryDays: 45,
  email: 'j.vance@apexdataworks.io',
  timezone: 'America/Los_Angeles (11:42 AM PST)',
  assignedRep: 'Sarah Chen (You)',
  direction: 'outbound',
  campaign: 'Q3 Enterprise Renewals (Outbound Connected)',
  duration: 222, // 03:42
  status: 'connected',
  isMuted: false,
  isOnHold: false,
  isRecording: true,
  sentiment: {
    score: 82,
    label: 'Positive',
    keywords: ['excited', 'upgrade', 'pricing tier', 'multi-region'],
  },
  notes: 'Jonathan is keen on migrating early before the 45-day window. Requested confirmation that the 15% multi-year discount covers their secondary disaster recovery trunk in Dallas. Mentioned VP of Tech needs to sign off by Thursday.',
  selectedDisposition: 'Contract Sent',
};

export const INITIAL_CRM_SYNC_LOGS: CrmSyncLog[] = [
  {
    id: 'crm-sync-01',
    syncId: 'SYNC-SF-9042',
    timestamp: '2026-09-26 14:34:30 EST',
    platform: 'Salesforce Service Cloud',
    trigger: 'AI Summary & Bulleted Takeaways',
    targetObject: 'Case #SF-90821 (Apex Global)',
    contactName: 'Jonathan Vance',
    company: 'Apex Global Dataworks Inc.',
    callId: 'CALL-20891',
    status: 'SUCCESS',
    httpStatusCode: 201,
    latencyMs: 142,
    retryCount: 0,
    maxRetries: 3,
    payloadSummary: {
      recordType: 'Case_Interaction_Telemetry__c',
      fieldsSynced: [
        'Case.SentimentScore__c',
        'Case.Disposition__c',
        'AI_ExecutiveSummary__c',
        'AI_BulletedTakeaways__c',
        'Call_Recording_URL__c',
      ],
      sentimentScore: 82,
      disposition: 'Contract Sent',
      hasRecording: true,
      hasAiSummary: true,
    },
  },
  {
    id: 'crm-sync-02',
    syncId: 'SYNC-HS-8120',
    timestamp: '2026-09-26 14:34:26 EST',
    platform: 'HubSpot CRM',
    trigger: 'Call Archival & Recording',
    targetObject: 'Deal #HS-8392 (BioHealth Corp)',
    contactName: 'Sarah Lin',
    company: 'BioHealth Corp',
    callId: 'CALL-92810',
    status: 'SUCCESS',
    httpStatusCode: 200,
    latencyMs: 118,
    retryCount: 0,
    maxRetries: 3,
    payloadSummary: {
      recordType: 'engagement_call',
      fieldsSynced: [
        'hs_call_title',
        'hs_call_duration',
        'hs_call_recording_url',
        'hs_call_sentiment_score',
        'hs_call_body',
      ],
      sentimentScore: 88,
      disposition: 'Follow Up Required',
      hasRecording: true,
      hasAiSummary: true,
    },
  },
  {
    id: 'crm-sync-03',
    syncId: 'SYNC-SF-9038',
    timestamp: '2026-09-26 14:28:15 EST',
    platform: 'Salesforce Service Cloud',
    trigger: 'Follow-Up Task Injection',
    targetObject: 'Task #SF-T4412 (FinTech Capital)',
    contactName: 'Marcus Sterling',
    company: 'FinTech Global Capital',
    callId: 'CALL-78192',
    status: 'FAILED',
    httpStatusCode: 429,
    latencyMs: 310,
    errorCode: 'ERR_API_RATE_LIMIT_EXCEEDED',
    errorMessage:
      'Salesforce REST API burst rate limit exceeded: 100 requests per rolling 20-second bucket on Connected App [AetherDial-Gateway-Prod]. Downstream 429 Too Many Requests.',
    retryCount: 2,
    maxRetries: 3,
    nextRetryAt: '2026-09-26 14:35:00 EST (Backoff 45s)',
    payloadSummary: {
      recordType: 'Task',
      fieldsSynced: ['Subject', 'ActivityDate', 'Priority', 'Description', 'WhoId'],
      sentimentScore: 89,
      disposition: 'Interested / Demo',
      hasRecording: false,
      hasAiSummary: true,
    },
  },
  {
    id: 'crm-sync-04',
    syncId: 'SYNC-DYN-4011',
    timestamp: '2026-09-26 14:22:25 EST',
    platform: 'Microsoft Dynamics 365',
    trigger: 'Voice Biometric Auth Verification',
    targetObject: 'Contact #DYN-3829 (SecureAuth)',
    contactName: 'David Kim',
    company: 'SecureAuth Networks',
    callId: 'CALL-61902',
    status: 'SUCCESS',
    httpStatusCode: 200,
    latencyMs: 164,
    retryCount: 0,
    maxRetries: 3,
    payloadSummary: {
      recordType: 'contact_auth_telemetry',
      fieldsSynced: [
        'msdyn_biometricverificationstatus',
        'msdyn_sentimentrating',
        'msdyn_callrecordinglink',
        'msdyn_dispositioncode',
      ],
      sentimentScore: 94,
      disposition: 'Completed Sale',
      hasRecording: true,
      hasAiSummary: true,
    },
  },
  {
    id: 'crm-sync-05',
    syncId: 'SYNC-ZD-3291',
    timestamp: '2026-09-26 14:15:40 EST',
    platform: 'Zendesk Enterprise',
    trigger: 'Disposition & Sentiment Update',
    targetObject: 'Ticket #ZD-44910 (Spam Deflected)',
    contactName: 'Unknown Caller',
    company: 'Spam Robo Deflection',
    callId: 'CALL-10291',
    status: 'SUCCESS',
    httpStatusCode: 200,
    latencyMs: 89,
    retryCount: 0,
    maxRetries: 3,
    payloadSummary: {
      recordType: 'ticket_audit_event',
      fieldsSynced: ['ticket.status', 'ticket.tags', 'ticket.custom_fields.dnc_flag'],
      sentimentScore: 10,
      disposition: 'Wrong Number / DNC',
      hasRecording: false,
      hasAiSummary: true,
    },
  },
  {
    id: 'crm-sync-06',
    syncId: 'SYNC-SNOW-2041',
    timestamp: '2026-09-26 14:08:12 EST',
    platform: 'ServiceNow CSM',
    trigger: 'Call Archival & Recording',
    targetObject: 'Incident #INC0091823 (Core Gateway)',
    contactName: 'Elena Rostova',
    company: 'BioHealth Corp',
    callId: 'CALL-48192',
    status: 'FAILED',
    httpStatusCode: 401,
    latencyMs: 412,
    errorCode: 'ERR_OAUTH_TOKEN_EXPIRED',
    errorMessage:
      'OAuth2 Bearer token expired on endpoint https://aetherdial.service-now.com/api/now/table/incident. Automatic token refresh failed with invalid_grant: client credentials revoked or rotated.',
    retryCount: 3,
    maxRetries: 3,
    payloadSummary: {
      recordType: 'incident_telephony_link',
      fieldsSynced: ['work_notes', 'close_code', 'impact', 'caller_id'],
      sentimentScore: 76,
      disposition: 'Interested / Demo',
      hasRecording: true,
      hasAiSummary: true,
    },
  },
  {
    id: 'crm-sync-07',
    syncId: 'SYNC-HS-8114',
    timestamp: '2026-09-26 13:58:04 EST',
    platform: 'HubSpot CRM',
    trigger: 'AI Summary & Bulleted Takeaways',
    targetObject: 'Contact #HS-C9014 (BioHealth)',
    contactName: 'Elena Rostova',
    company: 'BioHealth Corp',
    callId: 'CALL-48192',
    status: 'SUCCESS',
    httpStatusCode: 201,
    latencyMs: 122,
    retryCount: 0,
    maxRetries: 3,
    payloadSummary: {
      recordType: 'crm_note_ai_takeaways',
      fieldsSynced: ['hs_note_body', 'hs_sentiment', 'hs_takeaways_json'],
      sentimentScore: 76,
      disposition: 'Interested / Demo',
      hasRecording: true,
      hasAiSummary: true,
    },
  },
  {
    id: 'crm-sync-08',
    syncId: 'SYNC-SF-9021',
    timestamp: '2026-09-26 13:42:19 EST',
    platform: 'Salesforce Service Cloud',
    trigger: 'Disposition & Sentiment Update',
    targetObject: 'Opportunity #SF-OPP881 (Apex Global)',
    contactName: 'Jonathan Vance',
    company: 'Apex Global Dataworks Inc.',
    callId: 'CALL-20891',
    status: 'SUCCESS',
    httpStatusCode: 200,
    latencyMs: 155,
    retryCount: 0,
    maxRetries: 3,
    payloadSummary: {
      recordType: 'OpportunityStageUpdate',
      fieldsSynced: ['StageName', 'Probability', 'NextStep', 'ExpectedRevenue'],
      sentimentScore: 82,
      disposition: 'Contract Sent',
      hasRecording: false,
      hasAiSummary: false,
    },
  },
];
